version: '3'

services:
  api:
    container_name: api
    build:
      context: ./
    networks:
      - default
    ports:
      - "3333:3333"
    depends_on: 
      - mysql
      - postgresql

    environment: 
      APP_SECRET: mySecretKey
      POSTGRES_URL: postgres://admin:admin@postgresql:5432/mercafacil
      POSTGRES_CONNECTION: prod_postgres_database
      MYSQL_URL: jdbc:mysql://admin:admin@mysql:3306/mercafacil
      MYSQL_CONNECTION: prod_mysql_database

  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mercafacil
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_HOST: "%"

    command: --default-authentication-plugin=mysql_native_password
    networks:
      - default

  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    ports:
      - 5432
    environment:
      POSTGRES_DB: mercafacil
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    networks:
      - default

networks:
  default:
    ipam: 
      driver: default
